<?php

namespace Opencontent\Installer;

use Throwable;

class Steps extends AbstractStepInstaller implements InterfaceStepInstaller
{
    private static $index = 0;

    private $installerFactory;

    private $steps = [];

    public function __construct(StepInstallerFactory $stepFactory)
    {
        $this->installerFactory = $stepFactory;
    }

    public function setStep($step)
    {
        parent::setStep($step); // TODO: Change the autogenerated stub
        $this->steps = $step['steps'] ?? [];

    }

    public function dryRun(): void
    {
        foreach ($this->steps as $step) {
            $this->run($step, true);
        }
    }

    public function install(): void
    {
        foreach ($this->steps as $step) {
            $this->run($step, false);
        }
    }

    private function run(array $step, bool $dryRun): void
    {
        self::$index++;
        $index = self::$index;

        $stepName = isset($step['identifier']) ? $step['type'] . ' ' . $step['identifier'] : $step['type'];
        $this->logger->debug("[$index] $stepName");

        $ignoreError = false;
        if (isset($step['ignore_error'])) {
            $ignoreError = (bool)$step['ignore_error'];
        }
        if (isset($step['condition']) && $step['condition'] == '$is_install_from_scratch' && !$this->installerVars['is_install_from_scratch']) {
            $ignoreError = true;
        }
        $installer = $this->installerFactory->factoryByType($step['type']);

        try {
            $canInstallByVersionConstraint = $this->isStepInstallableByVersionConstraint($step);

            if ($canInstallByVersionConstraint) {
                $installer->setStep($step);

                $skip = false;
                if (isset($installer->getStep()['condition']) && (bool)$installer->getStep()['condition'] !== true) {
                    $this->logger->debug(" -> $stepName skipped by condition parameter");
                    $skip = true;
                }

                if (!$skip) {
                    if ($dryRun) {
                        $installer->dryRun();
                        if ($this->installerFactory->isWaitForUser() && !$this->waitForUser('  -> next step?')) {
                            throw new \RuntimeException('Aborted');
                        }
                    } elseif ($this->installerFactory->isWaitForUser()) {
                        $installer->dryRun();
                        if ($this->waitForUser(' -> install step?')) {
                            $installer->install();
                        }
                    } else {
                        $installer->install();
                    }
                }
            }
        } catch (Throwable $e) {
            if ($ignoreError) {
                $this->getLogger()->error($e->getMessage());
            } else {
                throw $e;
            }
        }
    }

    public function appendStep(array $step): void
    {
        $this->steps[] = $step;
    }

    private function isStepInstallableByVersionConstraint($step): bool
    {
        $skip = false;
        $currentVersion = $this->installerFactory->getCurrentVersion();
        $countVersionCheck = 0;
        $versionCheckValidCount = 0;
        $skipByVersionDebug = [];

        $availableConditions = [
            [
                'directive' => 'current_version_lt',
                'string_operator' => 'lt',
                'operator' => '<',
            ],
            [
                'directive' => 'current_version_le',
                'string_operator' => 'le',
                'operator' => '<=',
            ],
            [
                'directive' => 'current_version_eq',
                'string_operator' => 'eq',
                'operator' => '=',
            ],
            [
                'directive' => 'current_version_ge',
                'string_operator' => 'ge',
                'operator' => '>=',
            ],
            [
                'directive' => 'current_version_gt',
                'string_operator' => 'gt',
                'operator' => '>',
            ],
        ];

        foreach($availableConditions as $condition){
            $directive = $condition['directive'];
            if (isset($step[$directive])) {
                $check = version_compare(
                    $currentVersion,
                    $step[$directive],
                    $condition['string_operator']
                );
                if ($check) {
                    $versionCheckValidCount++;
                }
                $skipByVersionDebug[$directive] = implode(' ', [
                    $currentVersion,
                    $condition['operator'],
                    $step[$directive],
                    '->',
                    (int)$check
                ]);
                $countVersionCheck++;
            }
        }
        if ($countVersionCheck > 0) {
            foreach ($skipByVersionDebug as $skipCond => $skipDebug) {
                $this->logger->debug(" -> version compare: $skipCond $skipDebug");
            }
            $skip = $countVersionCheck != $versionCheckValidCount;
            if ($skip) {
                $this->logger->debug(
                    " -> skipped by version compare parameters ($versionCheckValidCount/$countVersionCheck)"
                );
            }
        }

        return $skip === false;
    }

    private function waitForUser(string $question): bool
    {
        return \ezcConsoleDialogViewer::displayDialog(
                \ezcConsoleQuestionDialog::YesNoQuestion(
                    new \ezcConsoleOutput(),
                    $question,
                    'y'
                )
            ) === 'y';
    }
}